version: '3.8'

services:
#  mysql:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_DATABASE: mysql
#      MYSQL_USER: root
#      MYSQL_PASSWORD: rootpassword
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"  # Exposing Redis port
    volumes:
      - redis_data:/data  # Persistent storage for Redis data



volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local


